name: backend deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn test
  