name: Deploy Backend

on:
  push:
    branches:
      - boom
    paths:
      - "backend/**"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      S3_NAME: ${{ secrets.S3_NAME }}
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: yarn and destroy
      run: |
        yarn install --frozen-lockfile
        yarn deploy --stage dev
    - name: upload csv
      run: STAGE=dev yarn scripts:upload
        
  