name: Destroy Backend

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'stage to destroy'
        required: true 
        type: string

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      S3_NAME: ${{ secrets.S3_NAME }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: destroy
      run: |
        yarn install --frozen-lockfile
        yarn destroy --stage ${{ github.event.inputs.stage }}

        